### ISSUE TITLE
TODO before the NSDF AHM

### ISSUE THREAD

**Issue by kevincoakley** [kevincoakley/osn-discovery-webui#18]
- [x] Fix bug with version v1.0.1 where the directory listings do not update. View the contents of one bucket, go back with the browser, then view the contents of a second bucket and the directory listing will show the first bucket's contents. This issue isn't present on commit eb570cc
- [x] Add the OSN & NSDF Logos to the top or bottom of the page. 

Logos:

https://www.openstoragenetwork.org/wp-content/uploads/2021/09/cropped-osn-logo-wonwhite.jpg
https://nationalsciencedatafabric.org/assets/images/logo.png

**Comment by AlexNguyenJJ** [comment]
Completed adding Logos to bottom of page

**Comment by AlexNguyenJJ** [comment]
Note that bottom bar `About` and `Contact Us` links don't lead to anywhere yet i.e. they are "broken links"

**Comment by AlexNguyenJJ** [comment]
Migrated to use of @tanstack/react-query for data fetching. Should fix the issue in regards to directory listings not updating correctly
